SELECT
    EVENT_ID,
    EVENT_TIMESTAMP,
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    TRIM(USER_ID) AS USER_ID,
    UPPER(TRIM(ACTION)) AS ACTION
FROM {{ source('ecommerce_raw', 'events') }}
WHERE EVENT_ID IS NOT NULL
