SELECT
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    UPPER(TRIM(COLOR)) AS COLOR,
    UPPER(TRIM(SECTION)) AS SECTION,
    TRIM(DESCRIPTION) AS DESCRIPTION,
    UPDATED_AT
FROM {{ source('ecommerce_raw', 'products') }}
WHERE PRODUCT_ID IS NOT NULL