CREATE OR REPLACE  FILE FORMAT CUSTOMER_RAW_LINE_FORMAT
TYPE = CSV
FIELD_DELIMITER=','
SKIP_HEADER=1
TRIM_SPACE=TRUE
EMPTY_FIELD_AS_NULL=TRUE;

CREATE OR REPLACE STORAGE INTEGRATION GSC_INTEGRATION
TYPE=EXTERNAL_STAGE
STORAGE_PROVIDER='GCS'
ENABLED=TRUE
STORAGE_ALLOWED_LOCATIONS=
(
'gcs://azctsdemo1bucket/input/snowsql/'
);

SHOW INTEGRATIONS;

DESC STORAGE INTEGRATION GSC_INTEGRATION;


CREATE OR REPLACE STAGE CUSTOMER_GCS_STAGE
URL='gcs://azctsdemo1bucket/input/snowsql/'
STORAGE_INTEGRATION=GSC_INTEGRATION;

LIST @CUSTOMER_GCS_STAGE;

SELECT $1 AS CUSTOMER_ID,$2 AS CUSTOMER_NAME,$3 AS CITY, $4 AS COUNTRY 
FROM @CUSTOMER_GCS_STAGE/customers.csv
(FILE_FORMAT => 'CUSTOMER_RAW_LINE_FORMAT')
LIMIT 10;


COPY INTO CUSTOMERS
FROM @CUSTOMER_GCS_STAGE/customers.csv
FILE_FORMAT= CUSTOMER_RAW_LINE_FORMAT
ON_ERROR='CONTINUE';

SELECT * FROM CUSTOMERS;