SELECT UPPER('geetha');


SELECT * FROM CUSTOMERS ORDER BY CUSTOMER_ID;

SELECT 
CUSTOMER_NAME,
TOTAL_SPEND,
CASE 
    WHEN TOTAL_SPEND> 40000 THEN 'VIP'
    WHEN TOTAL_SPEND>= 20000 THEN 'PREMIUM'
    ELSE 'STANDARD'
END AS CUSTOMER_CATEGORY
FROM CUSTOMERS;


-- UDF SYNTAX

CREATE OR REPLACE FUNCTION DOUBLE_VALUE(NUMBER_VALUE NUMBER)
RETURNS NUMBER
LANGUAGE SQL
AS
$$
    NUMBER_VALUE*2
$$;

SELECT  DOUBLE_VALUE(4);

SELECT  DOUBLE_VALUE(12);


CREATE OR REPLACE FUNCTION ADD_TAX(AMOUNT NUMBER)
RETURNS NUMBER
LANGUAGE SQL
AS
$$
    AMOUNT * 1.18
$$;


SELECT ADD_TAX(1000);

SELECT 
CUSTOMER_NAME,
TOTAL_SPEND, 
ADD_TAX(TOTAL_SPEND) AS AMOUNT_WITH_TAX
FROM CUSTOMERS;



--SCALAR UDF

CREATE OR REPLACE FUNCTION GET_CUSTOMER_CATEGORY(TOTAL_AMOUNT NUMBER)
RETURNS  VARCHAR
LANGUAGE SQL
AS
$$
    CASE 
        WHEN TOTAL_AMOUNT> 40000 THEN 'VIP'
        WHEN TOTAL_AMOUNT>= 20000 THEN 'PREMIUM'
        ELSE 'STANDARD'
    END
$$;

SELECT GET_CUSTOMER_CATEGORY(34000);


--APPLY UDF TO YOUR TABLE

SELECT
CUSTOMER_ID,
CUSTOMER_NAME,
TOTAL_SPEND,
GET_CUSTOMER_CATEGORY(TOTAL_SPEND) AS CUSTOMER_CATEGORY
FROM CUSTOMERS ORDER BY CUSTOMER_ID;


-- UDF WITH MULTIPLE PARAMETERS

CREATE OR REPLACE FUNCTION CUSTOMER_LABEL(NAME VARCHAR,COUNTRY_NAME VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
 NAME || ' - ' || COUNTRY_NAME
$$;


SELECT CUSTOMER_LABEL('Tina','Canada')

SELECT
CUSTOMER_ID,
CUSTOMER_LABEL(
CUSTOMER_NAME,COUNTRY)
AS CUSOMTER_DISPLAY 
FROM CUSTOMERS;

SELECT * FROM CUSTOMERS;

CREATE OR REPLACE FUNCTION AGE_GROUP(AGE_VALUE NUMBER)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
    CASE
        WHEN AGE_VALUE <30 THEN 'YOUNG ADULT'
        WHEN AGE_VALUE <40 THEN 'ADULT'
        ELSE 'SENIOR CUSTOMER'
    END
$$;

SELECT CUSTOMER_NAME,
AGE,
AGE_GROUP(AGE) AS AGE_CATEGORY
FROM CUSTOMERS 
ORDER BY AGE;

SELECT
CUSTOMER_ID,
CUSTOMER_LABEL(CUSTOMER_NAME,COUNTRY) AS CUSTOEMR,
AGE_GROUP(AGE) AS AGE_GROUP,
GET_CUSTOMER_CATEGORY(TOTAL_SPEND) AS SPENDING_CATEGORY
FROM CUSTOMERS;


SELECT CUSTOMER_NAME,
TOTAL_SPEND
FROM CUSTOMERS
WHERE GET_CUSTOMER_CATEGORY(TOTAL_SPEND)='VIP';

SELECT
GET_CUSTOMER_CATEGORY(TOTAL_SPEND) AS CUSTOMER_CATEGORY,
 COUNT(*) AS CUSTOMER_COUNT,
 SUM(TOTAL_SPEND) AS TOTAL_REVENUE
 FROM CUSTOMERS
 GROUP BY GET_CUSTOMER_CATEGORY(TOTAL_SPEND)
 ORDER BY TOTAL_REVENUE DESC;


 SHOW FUNCTIONS;