USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE DBT_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE DBT_TRAINING_DB;

CREATE OR REPLACE SCHEMA DBT_TRAINING_DB.RAW;

CREATE OR REPLACE SCHEMA DBT_TRAINING_DB.ANALYTICS;

CREATE OR REPLACE TABLE DBT_TRAINING_DB.RAW.CUSTOMERS
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    COUNTRY VARCHAR
);

INSERT INTO DBT_TRAINING_DB.RAW.CUSTOMERS
VALUES
(1,'Ravi','IN'),
(2,'John','US'),
(3,'Priya','IN'),
(4,'Sara','UK');


CREATE OR REPLACE TABLE DBT_TRAINING_DB.RAW.ORDERS
(
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    AMOUNT NUMBER,
    STATUS VARCHAR
);

INSERT INTO DBT_TRAINING_DB.RAW.ORDERS
VALUES
(1001,1,5000,'COMPLETED'),
(1002,1,2000,'COMPLETED'),
(1003,2,3000,'CANCELLED'),
(1004,3,9000,'COMPLETED'),
(1005,4,4000,'COMPLETED');


SELECT * FROM DBT_TRAINING_DB.ANALYTICS.MY_FIRST_DBT_MODEL;

SELECT * FROM DBT_TRAINING_DB.ANALYTICS.MY_SECOND_DBT_MODEL;

SELECT * FROM DBT_TRAINING_DB.ANALYTICS.STG_CUSTOMERS;