USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE SNOWFLAKE_TRAINING_DB;

CREATE OR REPLACE SCHEMA SNOWFLAKE_TRAINING_DB.BULK_LOAD_DEMO;


CREATE OR REPLACE WAREHOUSE TRAINING_WH
WAREHOUSE_SIZE= 'XSMALL'
AUTO_SUSPEND=300
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;

USE WAREHOUSE TRAINING_WH;

CREATE OR REPLACE TABLE CONTACTS(
ID INTEGER,
LAST_NAME STRING,
FIRST_NAME STRING,
COMPANY STRING,
EMAIL STRING,
WORKPHONE STRING,
CELLPHONE STRING,
STREETADDRESS STRING,
CITY STRING,
POSTALCODE STRING
);

SELECT * FROM SNOWFLAKE_TRAINING_DB.BULK_LOAD_DEMO.CONTACTS;

--FILE FORMAT

CREATE OR REPLACE FILE FORMAT CONTACTS_CSV_FORMAT
TYPE='CSV',
FIELD_DELIMITER='|',
SKIP_HEADER=1,
TRIM_SPACE=TRUE,
EMPTY_FIELD_AS_NULL=TRUE;


CREATE OR REPLACE STAGE CONTACTS_PUBLIC_STAGE
URL='S3://snowflake-docs'
FILE_FORMAT=CONTACTS_CSV_FORMAT;

LIST @CONTACTS_PUBLIC_STAGE/tutorials/dataloading/;

SELECT 
$1 AS ID,
$2 AS LAST_NAME,
$3 AS FIRST_NAME,
$4 AS COMPANY,
$5 AS EMAIL,
$6 AS WORKPHONE,
$7 AS CELLPHONE,
$8 AS STREETADDRESS,
$9 AS CITY,
$10 AS POSTALCODE
FROM @CONTACTS_PUBLIC_STAGE/tutorials/dataloading/contacts1.csv
(FILE_FORMAT => CONTACTS_CSV_FORMAT);

COPY INTO CONTACTS
FROM @CONTACTS_PUBLIC_STAGE/tutorials/dataloading/contacts1.csv
FILE_FORMAT =CONTACTS_CSV_FORMAT
VALIDATION_MODE='RETURN_ERRORS';

COPY INTO CONTACTS
FROM @CONTACTS_PUBLIC_STAGE/tutorials/dataloading/contacts1.csv
FILE_FORMAT =CONTACTS_CSV_FORMAT
ON_ERROR='ABORT_STATEMENT';

SELECT * FROM SNOWFLAKE_TRAINING_DB.BULK_LOAD_DEMO.CONTACTS;

SELECT * FROM CONTACTS ORDER BY ID DESC;

SELECT CURRENT_ROLE(),
CURRENT_DATABASE(),
CURRENT_SCHEMA(),
CURRENT_WAREHOUSE();

DESC TABLE CONTACTS;

DESC FILE FORMAT CONTACTS_CSV_FORMAT;

DESC STAGE CONTACTS_PUBLIC_STAGE;

LIST @CONTACTS_PUBLIC_STAGE/tutorials/dataloading/;


-- how to load multiple files

COPY INTO CONTACTS 
FROM @CONTACTS_PUBLIC_STAGE/tutorials/dataloading/
FILES= (
'contacts2.csv',
'contacts3.csv'
)
FILE_FORMAT = CONTACTS_CSV_FORMAT
ON_ERROR ='CONTINUE';

SELECT COUNT(*) FROM snowflake_training_db.bulk_load_demo.contacts;

COPY INTO CONTACTS 
FROM @CONTACTS_PUBLIC_STAGE/tutorials/dataloading/
PATTERN= '.*contacts[45]\.csv'
FILE_FORMAT = CONTACTS_CSV_FORMAT
ON_ERROR ='CONTINUE';