CREATE OR REPLACE WAREHOUSE SNOWPIPE_DEMO_WH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=180
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;


CREATE OR REPLACE DATABASE SNOWPIPE_DEMO_DB;

CREATE OR REPLACE SCHEMA SNOWPIPE_DEMO_DB.DEMO;

USE WAREHOUSE SNOWPIPE_DEMO_WH;
USE DATABASE SNOWPIPE_DEMO_DB;
USE SCHEMA DEMO;


CREATE OR REPLACE TABLE CUSTOMERS
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR,
    AGE NUMBER,
    SEGMENT VARCHAR,
    TOTAL_SPEND NUMBER(10,2)
);


SELECT * FROM CUSTOMERS;

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE=CSV
FIELD_DELIMITER=','
SKIP_HEADER=1
TRIM_SPACE=TRUE
EMPTY_FIELD_AS_NULL=TRUE;

DESC FILE FORMAT CUSTOMER_CSV_FORMAT;

CREATE OR REPLACE STORAGE INTEGRATION GCS_SNOWPIPE_STORAGE_INT
TYPE=EXTERNAL_STAGE
STORAGE_PROVIDER='GCS'
ENABLED=TRUE
STORAGE_ALLOWED_LOCATIONS= ('gcs://azctsdemo1bucket/input/snowpipe' );

DESC STORAGE INTEGRATION GCS_SNOWPIPE_STORAGE_INT;


CREATE OR REPLACE STAGE CUSTOMER_GCS_STAGE
URL='gcs://azctsdemo1bucket/input/snowpipe'
STORAGE_INTEGRATION=GCS_SNOWPIPE_STORAGE_INT
FILE_FORMAT=CUSTOMER_CSV_FORMAT;

DESC STAGE @CUSTOMER_GCS_STAGE;


LIST @CUSTOMER_GCS_STAGE;

CREATE OR REPLACE NOTIFICATION INTEGRATION
GCS_SNOWPIPE_NOTIFICATION_INT
TYPE=QUEUE
NOTIFICATION_PROVIDER=GCP_PUBSUB
ENABLED=TRUE
GCP_PUBSUB_SUBSCRIPTION_NAME='projects/bigquery-optimization-lab/subscriptions/snowpipe-customer-sub';


DESC NOTIFICATION INTEGRATION GCS_SNOWPIPE_NOTIFICATION_INT;

CREATE OR REPLACE PIPE CUSTOMER_SNOWPIPE
AUTO_INGEST=TRUE
INTEGRATION='GCS_SNOWPIPE_NOTIFICATION_INT'
AS
COPY INTO CUSTOMERS
FROM @CUSTOMER_GCS_STAGE
FILE_FORMAT=CUSTOMER_CSV_FORMAT
ON_ERROR='CONTINUE';


SELECT SYSTEM$PIPE_STATUS(
'SNOWPIPE_DEMO_DB.DEMO.CUSTOMER_SNOWPIPE'
);

DESC NOTIFICATION INTEGRATION GCS_SNOWPIPE_NOTIFICATION_INT;

SHOW PIPES;

DESC PIPE CUSTOMER_SNOWPIPE;


SELECT SYSTEM$PIPE_STATUS(
'SNOWPIPE_DEMO_DB.DEMO.CUSTOMER_SNOWPIPE'
);


SELECT * FROM CUSTOMERS;
SELECT COUNT(*) FROM CUSTOMERS;