CREATE OR REPLACE WAREHOUSE STREAM_DEMO_WH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=180
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;


CREATE OR REPLACE DATABASE STREAM_DEMO_DB;

CREATE OR REPLACE SCHEMA STREAM_DEMO_DB.DEMO;

CREATE OR REPLACE TABLE ORDERS
(
ORDER_ID NUMBER,
CUSTOMER_NAME VARCHAR,
PRODUCT VARCHAR,
QUANTITY NUMBER,
AMOUNT NUMBER(10,2),
ORDER_STATUS VARCHAR
);

INSERT INTO ORDERS
VALUES
    (101, 'Ravi',   'Laptop',     1, 65000, 'PLACED'),
    (102, 'Priya',  'Mobile',     2, 40000, 'PLACED'),
    (103, 'Arun',   'Headphones', 1,  5000, 'PLACED'),
    (104, 'Divya',  'Keyboard',   2,  6000, 'PLACED');


    SELECT * FROM ORDERS;

    CREATE OR REPLACE STREAM ORDERS_STREAM
    ON TABLE ORDERS;
    
    SHOW STREAMS;



    SELECT * FROM ORDERS_STREAM;

    INSERT INTO ORDERS
VALUES
(
    105,
    'Kumar',
    'Monitor',
    1,
    15000,
    'PLACED'
);


UPDATE ORDERS
SET ORDER_STATUS='SHIPPED'
WHERE ORDER_ID=101;

SELECT * FROM ORDERS;

SELECT * FROM ORDERS_STREAM;


DELETE FROM ORDERS WHERE ORDER_ID=103;


SELECT * FROM ORDERS_STREAM
WHERE METADATA$ACTION='INSERT'
AND
METADATA$ISUPDATE=FALSE;

CREATE OR REPLACE TABLE NEW_ORDER_HISORY
(
ORDER_ID NUMBER,
CUSTOMER_NAME VARCHAR,
PRODUCT VARCHAR,
QUANTITY NUMBER,
AMOUNT NUMBER(10,2),
ORDER_STATUS VARCHAR
);


INSERT INTO NEW_ORDER_HISORY
SELECT 
ORDER_ID ,
CUSTOMER_NAME ,
PRODUCT ,
QUANTITY ,
AMOUNT,
ORDER_STATUS 
FROM ORDERS_STREAM
WHERE METADATA$ACTION='INSERT'
AND METADATA$ISUPDATE=FALSE;

SELECT * FROM NEW_ORDER_HISORY;

SELECT * FROM  ORDERS_STREAM;


SELECT SYSTEM$STREAM_HAS_DATA('ORDERS_STREAM');

