USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE TASK_DEMO_DB;

CREATE OR REPLACE SCHEMA TASK_DEMO_DB.ECOMMERCE;

USE DATABASE TASK_DEMO_DB;
USE SCHEMA ECOMMERCE;

CREATE OR REPLACE WAREHOUSE TASK_DEMO_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE TABLE ORDERS
(
    ORDER_ID       NUMBER,
    CUSTOMER_NAME  VARCHAR,
    PRODUCT_NAME   VARCHAR,
    ORDER_AMOUNT   NUMBER(10,2),
    ORDER_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

SELECT * FROM ORDERS;

CREATE OR REPLACE TABLE PROCESSED_ORDERS
(
    ORDER_ID        NUMBER,
    CUSTOMER_NAME   VARCHAR,
    PRODUCT_NAME    VARCHAR,
    ORDER_AMOUNT    NUMBER(10,2),
    ORDER_DATE      TIMESTAMP,
    PROCESSED_TIME  TIMESTAMP
);


SELECT * FROM  PROCESSED_ORDERS;

CREATE OR REPLACE STREAM ORDER_STREAM
ON TABLE ORDERS;

INSERT INTO ORDERS
(
    ORDER_ID,
    CUSTOMER_NAME,
    PRODUCT_NAME,
    ORDER_AMOUNT
)
VALUES
    (101, 'Ravi',  'Laptop',   75000),
    (102, 'Priya', 'Mouse',     1500),
    (103, 'John',  'Keyboard',  3000);


    SELECT * FROM ORDERS;

    SELECT * FROM ORDER_STREAM;

    SELECT SYSTEM$STREAM_HAS_DATA('ORDER_STREAM');


    --- TASK


    CREATE OR REPLACE TASK PROCESS_NEW_ORDERS_TASK
    WAREHOUSE=TASK_DEMO_WH
    SCHEDULE='1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('ORDER_STREAM')
    AS
    INSERT INTO PROCESSED_ORDERS
    (ORDER_ID,CUSTOMER_NAME,PRODUCT_NAME,ORDER_AMOUNT,ORDER_DATE,PROCESSED_TIME)
    SELECT
    ORDER_ID,CUSTOMER_NAME,PRODUCT_NAME,ORDER_AMOUNT,ORDER_DATE,CURRENT_TIMESTAMP()
    FROM ORDER_STREAM
    WHERE METADATA$ACTION='INSERT'
    AND METADATA$ISUPDATE=FALSE;


    ALTER TASK PROCESS_NEW_ORDERS_TASK RESUME;

    SHOW TASKS;

    SELECT * FROM PROCESSED_ORDERS;

    EXECUTE TASK PROCESS_NEW_ORDERS_TASK;

    ALTER TASK PROCESS_NEW_ORDERS_TASK SUSPEND;

    INSERT INTO ORDERS
(
    ORDER_ID,
    CUSTOMER_NAME,
    PRODUCT_NAME,
    ORDER_AMOUNT
)
VALUES
    (106, 'Anitha', 'Webcam', 5500);

       