USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE TABLE_DEMO_WH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=180
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;

CREATE OR REPLACE DATABASE TABLE_VIEW_DB;

CREATE OR REPLACE SCHEMA TABLE_VIEW_DB.ECOMMERCE;

SELECT edition
FROM SNOWFLAKE.ORGANIZATION_USAGE.ACCOUNTS
WHERE account_locator=CURRENT_ACCOUNT();

--PERMANANT TABLE
CREATE OR  REPLACE TABLE TABLE_VIEW_DB.ECOMMERCE.CUSTOMERS(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    REGION VARCHAR
)
DATA_RETENTION_TIME_IN_DAYS=7;


SELECT * FROM TABLE_VIEW_DB.ECOMMERCE.CUSTOMERS;

INSERT INTO TABLE_VIEW_DB.ECOMMERCE.CUSTOMERS VALUES
(1, 'Aarav',  'aarav@example.com',  'INDIA'),
(2, 'Emma',   'emma@example.com',   'USA'),
(3, 'Noah',   'noah@example.com',   'USA'),
(4, 'Diya',   'diya@example.com',   'INDIA'),
(5, 'Oliver', 'oliver@example.com', 'UK');


CREATE OR  REPLACE TABLE TABLE_VIEW_DB.ECOMMERCE.ORDERS(
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    CATEGORY VARCHAR,
    AMOUNT NUMBER(10,2),
    STATUS VARCHAR,
    ORDER_DATE DATE,
    REGION VARCHAR
)
DATA_RETENTION_TIME_IN_DAYS=7;

INSERT INTO TABLE_VIEW_DB.ECOMMERCE.ORDERS VALUES
(101,1,'LAPTOP',     75000,'COMPLETED','2026-08-01','INDIA'),
(102,2,'MOBILE',     45000,'COMPLETED','2026-08-01','USA'),
(103,3,'HEADPHONE',   5000,'PENDING',  '2026-08-02','USA'),
(104,4,'LAPTOP',     65000,'COMPLETED','2026-08-02','INDIA'),
(105,5,'TABLET',     30000,'COMPLETED','2026-08-03','UK'),
(106,1,'MOBILE',     40000,'CANCELLED','2026-08-03','INDIA'),
(107,2,'LAPTOP',     80000,'COMPLETED','2026-08-04','USA'),
(108,3,'TABLET',     28000,'COMPLETED','2026-08-04','USA'),
(109,4,'HEADPHONE',   7000,'PENDING',  '2026-08-05','INDIA'),
(110,5,'MOBILE',     50000,'COMPLETED','2026-08-05','UK'),
(111,1,'LAPTOP',     70000,'COMPLETED','2026-08-06','INDIA'),
(112,2,'TABLET',     35000,'COMPLETED','2026-08-06','USA');


--TRANSIENT TABLE

CREATE OR REPLACE TRANSIENT  TABLE TABLE_VIEW_DB.ECOMMERCE.ORDERS_STAGE
(
ORDER_ID NUMBER,
CUSTOMER_ID NUMBER,
CATEGORY VARCHAR,
AMOUNT NUMBER(10,2),
STATUS VARCHAR,
ORDER_DATE DATE,
REGION VARCHAR
);



INSERT INTO TABLE_VIEW_DB.ECOMMERCE.ORDERS
SELECT * FROM ORDERS WHERE STATUS='PENDING';

--TEMPORARY TABLE

CREATE OR REPLACE TEMPORARY TABLE TEMP_HIGH_VALUE_ORDERS AS
SELECT * FROM ORDERS 
WHERE AMOUNT >50000;

SHOW TABLES;

SELECT  * FROM CUSTOMERS;

SELECT * FROM ORDERS;

--NORMAL OR NON MATERIALISED VIEW;
CREATE OR REPLACE VIEW COMPLETED_ORDERS_V AS
SELECT ORDER_ID,CUSTOMER_ID,CATEGORY,AMOUNT,ORDER_DATE,REGION
FROM ORDERS
WHERE STATUS='COMPLETED';


SELECT * FROM COMPLETED_ORDERS_V;

INSERT INTO ORDERS VALUES
(113,3,'MOBILE',55000,'COMPLETED','2026-08-07','USA')



--SECURE VIEW

CREATE OR REPLACE SECURE VIEW CUSTOMERS_ORDER_SECURE_V AS
SELECT 
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    O.ORDER_ID,
    O.CATEGORY,
    O.AMOUNT,
    O.STATUS,
    O.REGION
FROM CUSTOMERS C 
JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;


SELECT * FROM 
CUSTOMERS_ORDER_SECURE_V
ORDER BY ORDER_ID;

-- MATERIALIZED 

CREATE OR REPLACE MATERIALIZED VIEW HIGH_VALUE_COMPLETED_ORDERS_MV AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    CATEGORY,
    AMOUNT,
    ORDER_DATE,
    REGION
FROM ORDERS
WHERE STATUS='COMPLETED'
 AND AMOUNT >=50000;

 SELECT * 
 FROM HIGH_VALUE_COMPLETED_ORDERS_MV
 ORDER BY AMOUNT DESC;

 INSERT INTO ORDERS VALUES
(114,3,'lENOVA LAPTOP',95000,'COMPLETED','2026-08-07','USA')

SHOW MATERIALIZED VIEWS;


--- RECURSIVE VIEW

CREATE OR REPLACE TABLE PRODUCT_CATEGORY
(
    CATEGORY_ID NUMBER,
    CATEGORY_NAME VARCHAR,
    PARENT_CATEGORY_ID NUMBER
);


INSERT INTO PRODUCT_CATEGORY VALUES
(1, 'ELECTRONICS', NULL),
(2, 'COMPUTERS',    1),
(3, 'MOBILE',       1),
(4, 'LAPTOP',       2),
(5, 'DESKTOP',      2),
(6, 'ANDROID',      3),
(7, 'IOS',          3);

CREATE OR REPLACE RECURSIVE VIEW CATEGORY_HIERARCHY_V
(
    CATEGORY_ID,
    CATEGORY_NAME,
    PARENT_CATEGORY_ID,
    LEVEL_NO,
    CATEGORY_PATH
)
AS

SELECT
    CATEGORY_ID,
    CATEGORY_NAME,
    PARENT_CATEGORY_ID,
    1 AS LEVEL_NO,
    CATEGORY_NAME AS CATEGORY_PATH

FROM PRODUCT_CATEGORY
WHERE PARENT_CATEGORY_ID IS NULL

UNION ALL

SELECT
    C.CATEGORY_ID,
    C.CATEGORY_NAME,
    C.PARENT_CATEGORY_ID,
    P.LEVEL_NO + 1,
    P.CATEGORY_PATH || ' > ' || C.CATEGORY_NAME

FROM PRODUCT_CATEGORY C

JOIN CATEGORY_HIERARCHY_V P
    ON C.PARENT_CATEGORY_ID = P.CATEGORY_ID;


SELECT * FROM
CATEGORY_HIERARCHY_V
ORDER BY LEVEL_NO,CATEGORY_ID


--TEMPORARY VIEW

CREATE OR REPLACE TEMPORARY VIEW TODAY_HIGH_VALUE_ORDER_V AS
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    CATEGORY,
    AMOUNT,
    REGION
    FROM ORDERS
    WHERE AMOUNT >=50000;


SHOW VIEWS;


SELECT * FROM CUSTOMERS;

CREATE OR REPLACE MASKING POLICY EMAIL_MASK AS
(EMAIL_VALUE VARCHAR)
RETURNS VARCHAR ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN')
        THEN EMAIL_VALUE
    ELSE '**********@MASKED.COM'
    END;


   ALTER TABLE CUSTOMERS
   MODIFY COLUMN EMAIL
   SET MASKING POLICY EMAIL_MASK;

   SELECT * FROM CUSTOMERS;

   USE ROLE SYSADMIN;